title: George Phillips # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 4+ years of commercial experience in analytics, engineering, sales and a master's degree in Computer Science from Plymouth University. Currently at SATAVIA, previously GeoSpock (geospatial analytics).
  <br><br>
  Still in template mode. Under Construction.
  <br><br>
  <a href="https://www.linkedin.com/in/george-phillips/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
